### ISSUE TITLE
Git Repository wird nicht erkannt

### ISSUE THREAD

**Issue by Flashget** [Skyr/scmversion-gradle-plugin#3]
Danke für die schnelle Lösung von https://github.com/Skyr/scmversion-gradle-plugin/issues/2
Bin jetzt zwar etwas weitergekommen, habe aber neues Problem:

Mein Git-Repository wird nicht erkannt. Vermutlich deswegen, weil mein .git-Ordner nicht im gleichen Ordner liegt wie mein .gradle file im project root.

Hier zu Veranschaulichung

```java
[main folder]
      |_________ [.git]
      |______ ___[config]
      |______ ___[src] => hier liegt die build.gradle datei und hier führe ich auch gradle assemble für mein projekt aus
```

Vielleicht kann man Git Repo mit Hilfe von jgit.status oder wie hier beschrieben: http://stackoverflow.com/questions/13586502/how-to-check-if-a-git-clone-has-been-done-already-with-jgit
besser erkennen?

Hab dann als temporäres Workaround im GitDetector.isInUse() immer true zurückgegeben und plugin neu gebaut

Leider kriege ich jetzt die Fehlermeldung
A problem occurred configuring root project 'src'.
> Failed to notify project evaluation listener.
   > org/eclipse/jgit/lib/Repository

:-(

Danke nochmal!

**Comment by tbutter** [comment]
Die Lösung brauche ich auch in meinem Projekt. Wird es bald ein neues Release geben?

**Comment by Skyr** [comment]
@tbutter bitte den aktuellen Master auschecken und probieren, ob der im vorigen Kommentar skizzierte Vorschlag taugt. Falls ja, mache ich ein Release 'draus.

**Comment by tbutter** [comment]
Funktioniert so bei mir mit scmRootSearchDepth = 1

**Comment by Skyr** [comment]
Prima :-) Habe das ganze als Version 0.6.3 verpackt.

**Comment by HaeL106** [comment]
nicht sicher ob ich das gleiche problem hab. unter pages wenn ich im branch master oder main auswählen soll gibt nur none zur Auswahl.. wo fehlt was ?
