### ISSUE TITLE
Can I use the project.version for dependencies (without usign a gradle multi-project)

### ISSUE THREAD

**Issue by nikolauskrismer** [Skyr/scmversion-gradle-plugin#4]
First, I want to thank you for this great plugin.
Before I found it, I had to keep my versions in both - git and gradle - up to date.
Thanks to the plugin this has been reduced to git only :-)

There is only one thing I can not handle right now.
Maybe someone can help me.

I have to projects using git. One project is the dependency of the other one.
Both projects use the same version numbers, so that if Project A is build it is used by Project B in the same version.

Until now I could solve it like this
projectA->build.gradle: Define version="v0.5.0"
projectB->build.gradle: Also define version="v0.5.0" and use "compile "myDomain:projectA:$project.version"" in dependencies.

How can I achieve the same thing using this plugin.
If I try it as before the version in the dependencies block is "unspecified" (I guess that at this point the version simply has not been set), so the error message is " Could not find myDomain:projectA:unspecified."

Is there anything I can do to solve this problem? I tried using taskGraph.whenReady and afterEvaluate, but nothing worked (or maybe I did it the wrong way...).

**Comment by Skyr** [comment]
Thanks for your feedback, I'm glad to hear someone finds this plugin useful :-)
Just let me clarify this: You have two projects (most likely in two different repos), and your workflow is something like this:
* Build project A
* (Locally) publish project A
* Build project B

The last step gives some error because the version is not (yet) properly set. Am I correct?

**Comment by nikolauskrismer** [comment]
Yes... that's what I am doing
(ok... not exactly... I am not publishing locally but to a remote sonatype nexus repository, but that's all that is different)

**Comment by Skyr** [comment]
Ok, so the problem is the hook order (i.e. when the plugin functionality is actually executed). Let's see if there is a way (or at least a workaround)…

**Comment by nikolauskrismer** [comment]
Ok... that's great.
Let me know, if I can help with anything (providing build-script or the test-projects)

**Comment by Skyr** [comment]
It's tricky. The plugin sets the version number after the project is initialized, i.e. the plugin settings are done. But this also means that you can't access the calculated project.version within your project file. I checked in a possible workaround - please test.

**Comment by nikolauskrismer** [comment]
Hmm... does not seem to work.
The error message is (projectB is "isochrone-web" which depends on projectA "isochrone") 
I hope I did the testing the right way (have never used a gradle plugin in a SNAPSHOT version before... I just build the jar and replaced it in my gradle cache).

```
> Could not resolve all dependencies for configuration ':runtimeCopy'.
   > Could not find at.uibk.dbis:isochrone:0-SNAPSHOT.
     Searched in the following locations:
         https://jcenter.bintray.com/at/uibk/dbis/isochrone/0-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.pom
         https://jcenter.bintray.com/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.jar
         https://repo1.maven.org/maven2/at/uibk/dbis/isochrone/0-SNAPSHOT/maven-metadata.xml
         https://repo1.maven.org/maven2/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.pom
         https://repo1.maven.org/maven2/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.jar
         https://repo.gradle.org/gradle/plugins-releases/at/uibk/dbis/isochrone/0-SNAPSHOT/maven-metadata.xml
         https://repo.gradle.org/gradle/plugins-releases/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.pom
         https://repo.gradle.org/gradle/plugins-releases/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.jar
         http://download.osgeo.org/webdav/geotools/at/uibk/dbis/isochrone/0-SNAPSHOT/maven-metadata.xml
         http://download.osgeo.org/webdav/geotools/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.pom
         http://download.osgeo.org/webdav/geotools/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.jar
         http://maven.geo-solutions.it/at/uibk/dbis/isochrone/0-SNAPSHOT/maven-metadata.xml
         http://maven.geo-solutions.it/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.pom
         http://maven.geo-solutions.it/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.jar
         http://dbis-nexus.uibk.ac.at/content/groups/isochrone/at/uibk/dbis/isochrone/0-SNAPSHOT/maven-metadata.xml
         http://dbis-nexus.uibk.ac.at/content/groups/isochrone/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.pom
         http://dbis-nexus.uibk.ac.at/content/groups/isochrone/at/uibk/dbis/isochrone/0-SNAPSHOT/isochrone-0-SNAPSHOT.jar
         http://nodejs.org/dist/v0-SNAPSHOT/ivy.xml
         http://nodejs.org/dist/v0-SNAPSHOT/isochrone.jar
     Required by:
         at.uibk.dbis:isochrone-web:0.5.1-SNAPSHOT
```

**Comment by Skyr** [comment]
I just tried the following:

* Install a snapshot build of the plugin using `./gradlew install`
* Create a test project with the following gradle build file:

```gradle
buildscript {
  repositories {
    mavenCentral()
    mavenLocal()
  }
  dependencies {
    classpath 'de.ploing.gradle:scmversion-gradle-plugin:0.6.4-SNAPSHOT'
  }
}

apply plugin: 'de.ploing.scmversion'
apply plugin: 'java'

repositories {
  mavenCentral()
}

dependencies {
  compile "org.apache.commons:commons-math:${version}"
}
```
* Put it in a new repo, commit it, add the tag `version-2.2`

In my test, this properly includes commons-math in version 2.2. Be careful to have the repo in a clean state (i.e. `git status` shows no modifications), otherwise the version will be 2.3-SNAPSHOT (resulting in an error noting that the desired version of commons-math does not exist).

**Comment by nikolauskrismer** [comment]
OK... even when using this approach I get the error above.
I do have some modifications in my repo, so the version gets increased to 2.3-SNAPSHOT (in your example), but I also have such a SNAPSHOT version available for the dependency I want to include...

The part I do not understand in the error message is that there is a "Required by: at.uibk.dbis:isochrone-web:0.5.1-SNAPSHOT", while the dependency searched is "isochrone-0-SNAPSHOT.jar". If the last one would be "isochrone-0.5.1-SNAPSHOT.jar" things would be found in my remote repository...

**Comment by Skyr** [comment]
Do you use the standard pattern (verson-x.y.z) for your tags? If not, did you properly configure your version scheme? "0-SNAPSHOT" hints to…
* no version tag was found (resulting in version number 0)
* your repo has modified files or is not on the revision with the version tag (resulting in the SNAPSHOT suffix)

**Comment by nikolauskrismer** [comment]
I do not use the standard pattern, but I configured it the right way :-)

Here is the config part:
```
scmversion {
	releaseTagPattern = 'v([0-9.]*)'
}
```

**Comment by Skyr** [comment]
Is the configuration above the dependency section? Can you post (or privately email) me your build script?

**Comment by nikolauskrismer** [comment]
No that's not the dependency section.... it is part of the buildfile (at "root level")
My build script can be viewed [here] (https://dbis-git.uibk.ac.at/krismer/isochrone-web/blob/master/build.gradle) for isochrone-web and [here] (https://dbis-git.uibk.ac.at/krismer/isochrone/blob/master/build.gradle) for it's dependency isochrone.

Note that the script above does not try to use the version in dependencies. Here it is still hard-coded (otherwise the CI-server would not compile the project). All that should be changed is commenting line #40 and uncommenting line #95.

Hope this helps a bit. If you like, I could also send you my build-file with the changes applied and using the 0.6.4-SNAPSHOT version by e-mail.

**Comment by Skyr** [comment]
I think you're running in the problem I described in the latest (and last) section of the readme. In [your gradle file](https://dbis-git.uibk.ac.at/krismer/isochrone-web/blob/master/build.gradle), you are reading `project.version` _before_ you are configuring the plugin (the `scmversion` section). At that point, your configuration has not yet been read by Gradle, thus the default version scheme is assumed, resulting in the version number 0.
Move the `scmversion` section above your `ext` section, replace
```gradle
versionIsochrone = '0.5.1-SNAPSHOT'
```
with
```gradle
versionIsochrone = project.version
```
or even more pessimistically:
```gradle
versionIsochrone = project.version.toString
```
and try again :-)

**Comment by nikolauskrismer** [comment]
Yes... that's the solution. Using versionIsochrone = project.version after the scmversion block worked (however, versionIsochrone = project.version.toString does not work :-))
Moving the scmproperty part before my "ext-block" solved the problem.

This seems to work with version 0.6.3 already (so there should be no need for 0.6.4-SNAPSHOT due to this issue)

**Comment by nikolauskrismer** [comment]
Would be great to change the readme to something like "use the scmversion block immediatly after the plugin definitions, since otherwise project.version is not useable in some blocks..."

**Comment by Skyr** [comment]
Setting the version is done using `gradle.afterProject`, which (according to the documentation) is called _after_ (fully) evaluating the project. So I don't think this will work with 0.6.3 (unless you have some lucky case involving a subproject or something similar).

**Comment by nikolauskrismer** [comment]
Hmm... ok... so if 0.6.4 fixes this a new version would be great.
For me version 0.6.3 worked only, because I forgot that I replaced the 0.6.3 version in my locale repo (with 0.6.4-SNAPSHOT).

So it would be great to have a new version soon (sorry for the confusion).

**Comment by Skyr** [comment]
Version bumped to 0.6.4
