### ISSUE TITLE
Does not reliably detect head tags

### ISSUE THREAD

**Issue by herkne** [Skyr/scmversion-gradle-plugin#5]
It works only if i use the command-line version for tagging.
If i use eclipse (based on jgit) to set a tag, GitOperations.getHeadTags() does not find the correct tag
and therefore always adds the -SNAPSHOT suffix to the version. With a jgit created tag the Ref contains a pointer to the commit referred to by the tag which must be resolved before comparing against the head. 

Instead of 

    if (headVersion.equalsIgnoreCase(entry.value.objectId.name))

you should should use something like this:

  Ref r = entry.value
  if (!r.peeled)
    r = repository.peel(r)
  if ((r.peeledObjectId != null && headVersion.equalsIgnoreCase(r.peeledObjectId.name)) ||
   headVersion.equalsIgnoreCase(r.objectId.name))
    result.add(entry.key)
  
Best regards, Hermann

**Comment by Skyr** [comment]
Interesting :-) Thanks for the pointer, I'll look into it when I have some time to spare.
In case you are eager to contribute, you might create a (currently failing) test case :-)  It should be a simple copy-paste of an existing test, but with a different zip file (one containing a repo with a tag set by egit).

**Comment by Skyr** [comment]
Whoot, awesome! Thanks for the pull request!
Merged, version bumped.
